version: '3'
services:
    ganache:
        image: "0xorg/ganache-cli:6.0.0"
        ports:
            - "8545:8545"
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=api
            - POSTGRES_PASSWORD=api
            - POSTGRES_DB=api
        # persist the postgres data to disk so we don't lose it
        # on rebuilds.
        volumes:
            - ./postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    mesh:
        image: 0xorg/mesh:9.0.1
        depends_on:
            - ganache
        restart: on-failure
        environment:
            ETHEREUM_RPC_URL: '${ETHEREUM_RPC_URL}'
            ETHEREUM_CHAIN_ID: '${CHAIN_ID}'
            USE_BOOTSTRAP_LIST: 'true'
            VERBOSITY: 3
            PRIVATE_KEY_PATH: ''
            WS_RPC_ADDR: '0.0.0.0:60557'
            HTTP_RPC_ADDR: '0.0.0.0:60556'
            BLOCK_POLLING_INTERVAL: '2s'
            ETHEREUM_RPC_MAX_REQUESTS_PER_24_HR_UTC: '150000'
        volumes:
          - ./0x_mesh:/usr/mesh/0x_mesh
        ports:
            - '60556:60556'
            - '60557:60557'
            - '60558:60558'
            - '60559:60559'
        command: |
            sh -c "waitForGanache () { until printf 'POST /\r\nContent-Length: 26\r\n\r\n{\"method\":\"net_listening\"}' | nc localhost 8545 | grep true; do continue; done }; waitForGanache && ./mesh"
    events-pipeline:
        depends_on: 
            - postgres
        image: 0xorg/event-pipeline@sha256:058e730018a8bdc31b1fdd68935eeb27bc728a0db579b41436c138cf73e830e1
        restart: always
        environment:
            ETHEREUM_RPC_URL: '${ETHEREUM_RPC_URL}'
            CHAIN_ID: '${CHAIN_ID}'
            POSTGRES_URI: 'postgresql://api:api@postgres/api'
    quoter:
        image: 883408475785.dkr.ecr.us-east-1.amazonaws.com/neptune/quoter:402d78919b45fe257cc1f9f5c956c0ee2d95a254
        depends_on:
            - ganache
        restart: on-failure
        environment:
            ALLOWED_API_KEYS: 'koolApiKey1,koolApikey2'
            SELL_TOKEN_ADDRESS: '0x0b1ba0af832d7c05fd64161e0db78e85978e8082'
            BUY_TOKEN_ADDRESS: '0x871dd7c2b4b25e1aa18728e9d5f2af4c4e431f5c'
            QUOTE_STRATEGY: 'demo_one_to_one'
            ORDER_EXPIRY: 10
            ETH_FROM: '0x5409ED021D9299bf6814279A6A1411A7e866A631'
            CHAIN_ID: 1337
            RPC_URL: 'http://ganache:8545'
            AUTH_METHOD: 'other'
            PRIVATE_KEY: 'f2f48ee19680706196e2e339e5da3491186e0c4c5030670656b0e0164837257d'
            POSTGRES_CONNECTION_STRING: 'whatever. quoter calls rebalancer now, which demands this.'
            REDIS_URL: 'whatever. not used'
        ports:
            - '4000:4000'
        command: |
            sh -c "waitForGanache () { until curl -s -d '{\"method\":\"net_listening\"}' http://ganache:8545 | grep true; do continue; done }; waitForGanache && cd quoter; yarn start"
