# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.12.0-browsers
            - image: circleci/postgres:9.6.5-alpine-ram
            - image: 0xorg/ganache-cli:6.0.0
            - image: 0xorg/mesh:9.0.1
              environment:
                ETHEREUM_RPC_URL: http://0.0.0.0:8545
                ETHEREUM_CHAIN_ID: 1337
                USE_BOOTSTRAP_LIST: 'true'
                VERBOSITY: 3
                PRIVATE_KEY_PATH: ''
                BLOCK_POLLING_INTERVAL: '2s'
                WS_RPC_ADDR: '0.0.0.0:60557'
                HTTP_RPC_ADDR: '0.0.0.0:60556'
                ETHEREUM_RPC_MAX_REQUESTS_PER_24_HR_UTC: '150000'
            - image: 883408475785.dkr.ecr.us-east-1.amazonaws.com/neptune/quoter:402d78919b45fe257cc1f9f5c956c0ee2d95a254
              aws_auth:
                  aws_access_key_id: $AWS_ACCESS_KEY_ID
                  aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
              environment:
                  ALLOWED_API_KEYS: 'koolApiKey1,koolApikey2'
                  SELL_TOKEN_ADDRESS: '0x0b1ba0af832d7c05fd64161e0db78e85978e8082'
                  BUY_TOKEN_ADDRESS: '0x871dd7c2b4b25e1aa18728e9d5f2af4c4e431f5c'
                  QUOTE_STRATEGY: 'demo_one_to_one'
                  ORDER_EXPIRY: 10
                  ETH_FROM: '0x5409ED021D9299bf6814279A6A1411A7e866A631'
                  CHAIN_ID: 1337
                  RPC_URL: 'http://0.0.0.0:8545'
                  AUTH_METHOD: 'other'
                  PRIVATE_KEY: 'f2f48ee19680706196e2e339e5da3491186e0c4c5030670656b0e0164837257d'
                  POSTGRES_CONNECTION_STRING: 'whatever. quoter calls rebalancer now, which demands this.'
                  REDIS_URL: 'whatever. not used'
        working_directory: ~/repo
        environment:
            ETHEREUM_RPC_URL: http://0.0.0.0:8545
            CHAIN_ID: 1337
            MESH_WEBSOCKET_URI: ws://0.0.0.0:60557
            MESH_HTTP_URI: http://0.0.0.0:60556
            POSTGRES_USER: postgres
            POSTGRES_DB: circle_test
            POSTGRES_URI: 'postgresql://root@localhost/circle_test'
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
            - run: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
            - run: yarn build
            - run: yarn lint
            - run: yarn prettier:ci
            - run: yarn test
